// <auto-generated />
using System;
using ConcentKitchen.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConcentKitchen.Migrations
{
    [DbContext(typeof(KitchenContext))]
    [Migration("20221214184043_CreateProductDishAndOrderTables")]
    partial class CreateProductDishAndOrderTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ConcentKitchen.Models.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("TableNumber")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ConcentKitchen.Models.Dish", b =>
                {
                    b.Property<Guid>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DishCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DishConclusionInMinutes")
                        .HasColumnType("int");

                    b.Property<string>("DishIngredients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DishName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("DishPrice")
                        .HasColumnType("real");

                    b.Property<Guid?>("OrderDishId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DishId");

                    b.HasIndex("OrderDishId");

                    b.ToTable("Dishes");
                });

            modelBuilder.Entity("ConcentKitchen.Models.Order", b =>
                {
                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CompletionDeadline")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderDishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("ClientId");

                    b.HasIndex("OrderDishId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ConcentKitchen.Models.OrderDish", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DishId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("OrderDish");
                });

            modelBuilder.Entity("ConcentKitchen.Models.Dish", b =>
                {
                    b.HasOne("ConcentKitchen.Models.OrderDish", null)
                        .WithMany("Dish")
                        .HasForeignKey("OrderDishId");
                });

            modelBuilder.Entity("ConcentKitchen.Models.Order", b =>
                {
                    b.HasOne("ConcentKitchen.Models.Client", "Client")
                        .WithMany("Orders")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConcentKitchen.Models.OrderDish", null)
                        .WithMany("Order")
                        .HasForeignKey("OrderDishId");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ConcentKitchen.Models.Client", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ConcentKitchen.Models.OrderDish", b =>
                {
                    b.Navigation("Dish");

                    b.Navigation("Order");
                });
#pragma warning restore 612, 618
        }
    }
}
